#!/bin/bash
#
# Architect Installation Framework (version 1.6.3 - 17-Dec-2015)
#
# Written by Carl Duff for Architect Linux
#
# This program is free software, provided under the GNU General Public License
# as published by the Free Software Foundation. So feel free to copy, distribute,
# or modify it as you wish.
#

######################################################################
##                                                                  ##
##                   Installer Variables                            ##
##                                                                  ##
######################################################################

# Create a temporary file to store menu selections
ANSWER="/tmp/.aif"
ABSOLUT_FILENAME=`readlink -e "$0"`
filesdir=`dirname "$ABSOLUT_FILENAME"`
# Save retyping
VERSION="MAXIMALISIMUS Installation Framework 2.3"

source "./modules/installer-variables.sh"                 # list of variables
source "./config/list-pkg-forms.sh"                       # list of packages for uses the script
source "./config/setup_function.sh"                       # Function to setup on local package, p.c. build package in aur
source "./config/package-manager_function.sh"             # Setup function to package manager - pamac
source "./config/package_function.sh"                     # Setup local package on build in aur
source "./config/emulators_function.sh"                   # Setup packages on emulators
source "./config/remove_old_v_pkg_function.sh"            # Remove duble package on old version
source "./config/dependences_function.sh"				  # Dependences for script
source "./modules/core-functions.sh"                      # language, checks
source "./modules/configuration-functions.sh"             # Keyboard, locale, time zone, FSTAB, mkinitcpio, user controls
source "./modules/system-partitioning.sh"                 # managing partitions, installing the boot
source "./modules/encryption-functions.sh"                # Encryption
source "./modules/logical-volume.sh"                      # LVM control
source "./modules/installation-functions.sh"              # system installation functions
source "./modules/swappiness-config.sh"                   # SWAPPINESS
source "./modules/devices-config.sh"                      # tune2fs
source "./modules/shell_installer.sh"                     # SHELL installer functions
source "./modules/main-interfaces.sh"                     # main menu interface

######################################################################
##                                                                  ##
##                        Execution                                 ##
##                                                                  ##
######################################################################

# sudo cp -f $filesdir/pacman.conf /etc/pacman.conf
setcolor
dialog 1>/dev/null 2>/dev/null
if [[ $? != "0" ]]; then
	script_dependences_question
	dependences_result
fi
id_system
select_language
clear
echo ""
find_and_remode "$_aur_pkg_folder"
multilib_question
check_requirements
greeting
    while true; do
          main_menu_online      
    done
