#!/bin/bash
#
# Architect Installation Framework (version 1.6.3 - 17-Dec-2015)
#
# Written by Carl Duff for Architect Linux
#
# This program is free software, provided under the GNU General Public License
# as published by the Free Software Foundation. So feel free to copy, distribute,
# or modify it as you wish.
#

######################################################################
##                                                                  ##
##                   Installer Variables                            ##
##                                                                  ##
######################################################################

# Create a temporary file to store menu selections
ANSWER="/tmp/.aif"
ABSOLUT_FILENAME=$(readlink -e "$0")
filesdir=$(dirname "$ABSOLUT_FILENAME")
# Save retyping
VERSION="MAXIMALISIMUS Installation Framework 2.5"

source "$filesdir"/config/dialogrc-conf.sh                        # Color dialog interface configured
source "$filesdir"/modules/installer-variables.sh                 # list of variables
source "$filesdir"/config/list-pkg-forms.sh                       # list of packages for uses the script
source "$filesdir"/config/setup_function.sh                       # Function to setup on local package, p.c. build package in aur
source "$filesdir"/config/package-manager_function.sh             # Setup function to package manager - pamac
source "$filesdir"/config/package_function.sh                     # Setup local package on build in aur
source "$filesdir"/config/emulators_function.sh                   # Setup packages on emulators
source "$filesdir"/config/remove_old_v_pkg_function.sh            # Remove duble package on old version
source "$filesdir"/config/dependences_function.sh                 # Dependences for script
source "$filesdir"/config/verify_package_folder.sh                # Check required folder and required files
source "$filesdir"/modules/core-functions.sh                      # language, checks
source "$filesdir"/modules/configuration-functions.sh             # Keyboard, locale, time zone, FSTAB, mkinitcpio, user controls
source "$filesdir"/modules/system-partitioning.sh                 # managing partitions, installing the boot
source "$filesdir"/modules/encryption-functions.sh                # Encryption
source "$filesdir"/modules/logical-volume.sh                      # LVM control
source "$filesdir"/modules/installation-functions.sh              # system installation functions
source "$filesdir"/modules/swappiness-config.sh                   # SWAPPINESS
source "$filesdir"/modules/devices-config.sh                      # tune2fs
source "$filesdir"/modules/shell_installer.sh                     # SHELL installer functions
source "$filesdir"/modules/main-interfaces.sh                     # main menu interface

######################################################################
##                                                                  ##
##                        Execution                                 ##
##                                                                  ##
######################################################################

setcolor
# /bin/bash -c "dialog --version" 1>/dev/null 2>/dev/null
pacman -Qs dialog 1>/dev/null 2>/dev/null
if [[ $? != "0" ]]; then
    script_dependences_question
    dependences_result
fi
us_dlgrc_conf
id_system
select_language
if [[ ${_archi[*]} == "x86_64" ]]; then
    multilib_question
    clear
#    /bin/bash -c "git --version" 1>/dev/null 2>/dev/null
    pacman -Qs git 1>/dev/null 2>/dev/null
    if [[ $? != "0" ]]; then
        sudo pacman -S git --noconfirm
    fi
    vrf_cnt_fls
    wait
    clear
    echo ""
    find_and_remode "$_aur_pkg_folder"
fi    
check_requirements
greeting
    while true; do
          main_menu_online      
    done
