#!/bin/bash
#
# Architect Installation Framework (version 1.6.3 - 17-Dec-2015)
#
# Written by Carl Duff for Architect Linux
#
# This program is free software, provided under the GNU General Public License
# as published by the Free Software Foundation. So feel free to copy, distribute,
# or modify it as you wish.
#

######################################################################
##                                                                  ##
##                   Installer Variables                            ##
##                                                                  ##
######################################################################

# Create a temporary file to store menu selections
ANSWER="/tmp/.aif"
ABSOLUT_FILENAME=$(readlink -e "$0")
filesdir=$(dirname "$ABSOLUT_FILENAME")
# Save retyping
VERSION="MAXIMALISIMUS Installation Framework 2.6"

find "$filesdir/config" -maxdepth 1 -type f -iname "*.sh" -exec source {} \;

find "$filesdir/modules" -maxdepth 1 -type f -iname "*.sh" -exec source {} \;

######################################################################
##                                                                  ##
##                        Execution                                 ##
##                                                                  ##
######################################################################

setcolor
question_dialog_run
us_dlgrc_conf
id_system
select_language
if [[ "${_archi[*]}" = "x86_64" ]]; then
    multilib_question
    wait
    clear
fi    
check_requirements
greeting
    while true; do
          main_menu_online      
    done
